// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SebineCizkekCayEviAPİ.Data;

#nullable disable

namespace SebineCizkekCayEviAPİ.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SebineCizkekCayEviAPİ.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$11$kz5NikZ7iEDFoInFegOYbupz1m.kEAdtPXpCU0zLTtUTkIcA75Syi",
                            Username = "Sebine Isgenderova"
                        });
                });

            modelBuilder.Entity("SebineCizkekCayEviAPİ.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("SebineCizkekCayEviAPİ.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("SebineCizkekCayEviAPİ.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "cheesecake",
                            CreatedDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Klassik resept, kremli texture",
                            ImageUrl = "/images/ny-cheesecake.jpg",
                            IsActive = true,
                            Name = "New York Cheesecake",
                            Price = 8m
                        },
                        new
                        {
                            Id = 2,
                            Category = "cheesecake",
                            CreatedDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Təzə vişnə ilə hazırlanıb",
                            ImageUrl = "/images/cherry-cheesecake.jpg",
                            IsActive = true,
                            Name = "Cherry Cheesecake",
                            Price = 9m
                        },
                        new
                        {
                            Id = 3,
                            Category = "cheesecake",
                            CreatedDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Təzə vişnə və şokolad ilə hazırlanıb",
                            ImageUrl = "/images/cherry-chocolate-cheesecake.jpg",
                            IsActive = true,
                            Name = "Cherry Chocolate Cheesecake",
                            Price = 10m
                        },
                        new
                        {
                            Id = 4,
                            Category = "cheesecake",
                            CreatedDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Təzə çiyələk ilə hazırlanıb",
                            ImageUrl = "/images/strawberry-cheesecake.jpg",
                            IsActive = true,
                            Name = "Strawberry Cheesecake",
                            Price = 9m
                        },
                        new
                        {
                            Id = 5,
                            Category = "cheesecake",
                            CreatedDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Təzə moruq ilə hazırlanıb",
                            ImageUrl = "/images/raspberry-cheesecake.jpg",
                            IsActive = true,
                            Name = "Raspberry Cheesecake",
                            Price = 9m
                        },
                        new
                        {
                            Id = 6,
                            Category = "cheesecake",
                            CreatedDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kokoslu krem qatları və ağ şokolad örtüyü",
                            ImageUrl = "/images/rafaello-cheesecake.jpg",
                            IsActive = true,
                            Name = "Raffaello Cheesecake",
                            Price = 9m
                        },
                        new
                        {
                            Id = 7,
                            Category = "cheesecake",
                            CreatedDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Oreo parça və krem ilə",
                            ImageUrl = "/images/oreo-cheesecake.jpg",
                            IsActive = true,
                            Name = "Oreo Cheesecake",
                            Price = 9m
                        },
                        new
                        {
                            Id = 8,
                            Category = "cheesecake",
                            CreatedDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lotus biskvit və karamel",
                            ImageUrl = "/images/lotus-cheesecake.jpg",
                            IsActive = true,
                            Name = "Lotus Cheesecake",
                            Price = 10m
                        },
                        new
                        {
                            Id = 9,
                            Category = "tort",
                            CreatedDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Zəngin şokolad qatları",
                            ImageUrl = "/images/chocolate-cake.jpg",
                            IsActive = true,
                            Name = "Chocolate Dream Cake",
                            Price = 7m
                        },
                        new
                        {
                            Id = 10,
                            Category = "tort",
                            CreatedDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Krem peynir ilə klassik",
                            ImageUrl = "/images/red-velvet.jpg",
                            IsActive = true,
                            Name = "Red Velvet",
                            Price = 8m
                        },
                        new
                        {
                            Id = 11,
                            Category = "tort",
                            CreatedDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Karamel sous ilə hazırlanıb",
                            ImageUrl = "/images/caramel-cake.jpg",
                            IsActive = true,
                            Name = "Caramel Cake",
                            Price = 7m
                        },
                        new
                        {
                            Id = 12,
                            Category = "çay",
                            CreatedDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Yerli plantasiyalardan",
                            ImageUrl = "/images/black-tea.jpg",
                            IsActive = true,
                            Name = "Azərbaycan Qara Çay",
                            Price = 3m
                        },
                        new
                        {
                            Id = 13,
                            Category = "çay",
                            CreatedDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bergamot aromalı klassik",
                            ImageUrl = "/images/earl-grey.jpg",
                            IsActive = true,
                            Name = "Earl Grey",
                            Price = 4m
                        },
                        new
                        {
                            Id = 14,
                            Category = "çay",
                            CreatedDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Antioksidant zəngin seçim",
                            ImageUrl = "/images/green-tea.jpg",
                            IsActive = true,
                            Name = "Yaşıl Çay",
                            Price = 4m
                        },
                        new
                        {
                            Id = 15,
                            Category = "çay",
                            CreatedDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mövsümi meyvələrlə blend",
                            ImageUrl = "/images/fruit-tea.jpg",
                            IsActive = true,
                            Name = "Meyvəli Çay",
                            Price = 5m
                        });
                });

            modelBuilder.Entity("SebineCizkekCayEviAPİ.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PeopleCount")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Reservations", (string)null);
                });

            modelBuilder.Entity("SebineCizkekCayEviAPİ.Models.OrderItem", b =>
                {
                    b.HasOne("SebineCizkekCayEviAPİ.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SebineCizkekCayEviAPİ.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SebineCizkekCayEviAPİ.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SebineCizkekCayEviAPİ.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
